config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/about', to: 'pages#about'
  get 'pages/home', to: 'pages#home'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users , except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true #, length: {minimum: 3, maximum: 100}
	validates :description, presence: true #, length: {minimum: 3, maximum: 300}
	# validates :user_id, presense: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles
	before_save {self.email = email.downcase}
	validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}, format: {with: VALID_EMAIL_REGEX}

	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

		before_action :set_article ,only:[:edit, :update, :show, :destroy]

		def index
			@articles = Article.all
		end

		def new
			@article = Article.new
		end

		def create
			@article = Article.new(article_params)	
			@article.user = User.last	
			if @article.save
				flash[:notice] = "article was created"
				redirect_to article_path(@article)
			else
				render 'new'
			end
		end

		def show #read
			# @article = Article.find(params[:id])
		end

		def edit #update
			# @article = Article.find(params[:id])
		end

		def update
			# @article = Article.find(params[:id])
			if @article.update(article_params)
				flash[:notice] = "article was updated"
				redirect_to article_path(@article)
			else
				render 'edit'
			end
		end

		def destroy
			# @article = Article.find(params[:id])
			@article.destroy
			flash[:notice] = "Article was deleted"
			redirect_to articles_path
		end

	
		 
	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)
	end



end

app/controllers/concerns/pages_controller.rb
class PagesController < ApplicationController # i just copied and pasted and thats why it broke. it needed to say "Application"
	def about
	end

	def home
	end
end

app/controllers/concerns/user_controller.rb
class UserController < ApplicationController
	def home
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController # i just copied and pasted and thats why it broke. it needed to say "Application"
	def about
	end

	def home
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		render 'new'
	end

	def destroy
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome to Alpha Blog #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end

	end

	def edit
		@user = User.find(params[:id])

	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success] = "user has been updated"
			redirect_to articles_path

		else
			render 'edit'
		end

	end

	def show
		@user = User.find(params[:id])
	end

	def index
		@users = User.all
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "rounded-circle")


	end
end

app/views/articles/_article.html.erb
<div>
	<%= link_to 'new article', new_article_path %>
</div>
<br>
<table border=1 class="container">
	<tr>
		<th>ID</th>
		<th>Title</th>
		<th>Description</th>
		<th>User ID</th>
		<th>Username</th>
		<th>Edit</th>
		<th>Show</th>
		<th>Delete</th>
	</tr>

	<% obj.each do |article| %> 

	<tr>
		<td><%= link_to article.id, article_path(article) %></td>
		<td><%= article.title %></td>
		<td><%= article.description %></td>
		<td><%= article.user_id %></td>
		<td><%= article.user.username if article.user %></td>
		<td><%= link_to 'edit', edit_article_path(article) %></td>
		<td><%= link_to 'show', article_path(article) %></td>
		<td><%= link_to 'delete', article_path(article), method: :delete, data: {confirm: "Are you sure"} %></td>
	</tr>

	<% end %>


</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
	<h2>Errors</h2>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<div>
	<div> 

		<%= form_for @article do |f| %>

		<div class="form-group row"> 
			<%= f.label :title, for: "input", class: "control-form-lable col-sm-2" %>
			<div class="col-sm-10">
				<%= f.text_field :title, class: "form-control" , placeholder: "Title for Article", autofocus: true  %>				
			</div>
		</div>


		<div class="form-group row"> 			
			<%= f.label :description, for: "input", class: "control-form-lable col-sm-2" %>
			<div class="col-sm-10">
				<%= f.text_area :description,rows: 10, class: "form-control", placeholder: "Article content", autofocus: true%>
			</div>	
		</div>

		<div class="form-group row">
			<div class="col-sm-10 offset-sm-2">
				<%= f.submit class: "btn btn-primary btn-lg" %>
			</div>
		</div>


		<% end %>
	</div>
</div>

<!-- <form>
  <div class="form-group row">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>
  <fieldset class="form-group">
    <div class="row">
      <legend class="col-form-label col-sm-2 pt-0">Radios</legend>
      <div class="col-sm-10">
        <div class="form-check">
          <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios1" value="option1" checked>
          <label class="form-check-label" for="gridRadios1">
            First radio
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="option2">
          <label class="form-check-label" for="gridRadios2">
            Second radio
          </label>
        </div>
        <div class="form-check disabled">
          <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios3" value="option3" disabled>
          <label class="form-check-label" for="gridRadios3">
            Third disabled radio
          </label>
        </div>
      </div>
    </div>
  </fieldset>
  <div class="form-group row">
    <div class="col-sm-2">Checkbox</div>
    <div class="col-sm-10">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="gridCheck1">
        <label class="form-check-label" for="gridCheck1">
          Example checkbox
        </label>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Sign in</button>
    </div>
  </div>
</form> -->

app/views/articles/edit.html.erb
<h1>Edit Post <%= @article.title %></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>List of Articles</h1>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1>create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<p><%= @article.description %></p>
<p><%= @article.id %></p>
<p><%= link_to 'edit', edit_article_path(@article) %></p>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="#">Link</a>
			by <a href="#"> by Dave</a>

		</small>
		<nav>
			<ul>
				<li><a href="#">About</a></li>
				<li><a href="#">link 2</a></li>
				<li><a href="#">link 3</a></li>
			</ul>
		</nav>
		
	</footer>
	
</div>

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg| %>
    <ul>
      <li> <%= msg %></li>
    </ul>
    <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <%= link_to 'Alpha blog', root_path, class: 'navbar-brand', id:'logo' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Articles', articles_path, class:'nav-link' %>
      </li>
     <li class="nav-item active">
        <%= link_to 'Users', users_path, class:'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create Article", new_article_path, class:'dropdown-item'%>
          <%= link_to "Create User",'#', class:'dropdown-item'%>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'About', pages_about_path, class:'nav-link'%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<%= link_to 'home', root_path %>

app/views/pages/home.html.erb
<div class="jumbotron center bg-image">
  <h1 class="display-3">ALPHA BLOG</h1>

  <%= link_to "Sign Up Now","#", class: "btn btn-danger btn-lg btn-xlarge" %>

</div>

app/views/users/_form.html.erb
<div>
	<div> 

		<%= form_for @user do |f| %>

		<div class="form-group row"> 
			<%= f.label :username, for: "input", class: "control-form-lable col-sm-2" %>
			<div class="col-sm-10">
				<%= f.text_field :username, class: "form-control" , placeholder: "username", autofocus: true  %>				
			</div>
		</div>


		<div class="form-group row"> 			
			<%= f.label :email, for: "input", class: "control-form-lable col-sm-2" %>
			<div class="col-sm-10">
				<%= f.email_field :email, class: "form-control", placeholder: "email", autofocus: true%>
			</div>	
		</div>

		<div class="form-group row"> 			
			<%= f.label :password, for: "input", class: "control-form-lable col-sm-2" %>
			<div class="col-sm-10">
				<%= f.password_field :password, class: "form-control", placeholder: "password", autofocus: true%>
			</div>	
		</div>

		<div class="form-group row">
			<div class="col-sm-10 offset-sm-2">
				<%= f.submit(@user.new_record? ? "Sign Up" : "Upate Account", class: "btn btn-primary btn-lg") %>
			</div>
		</div>


		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Users</h1>
<table class="container">
	<tr>
		<th>id</th>
		<th>username</th>
		<th>email</th>
		<th>Edit</th>
	</tr>
	<% @users.each do |user| %>

	<tr>
		<td><%= link_to user.id, user_path(user) %></td>
		<td><%= user.username %></td>
		<td><%= user.email %></td>
		<td><%= link_to 'edit', edit_user_path(user) %></td>
	</tr>
	<% end %>

</table>

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Hello <%= @user.username %>!!</h1>

<div class="row">
	<div class="col-md-4 offset-4 center" >
		<%= gravatar_for @user, size: 150 %>
	</div>


</div>

<div>
	<%= render 'articles/article', obj: @user.articles %>
</div>